"""empty message

Revision ID: 83c6bd30bfdb
Revises: 
Create Date: 2020-05-15 17:37:57.496502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c6bd30bfdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('user_name', sa.String(length=32), nullable=True),
    sa.Column('user_email', sa.String(length=32), nullable=True),
    sa.Column('user_photo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payer_email', sa.String(length=100), nullable=True),
    sa.Column('unix', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.String(length=100), nullable=True),
    sa.Column('item_type', sa.String(length=100), nullable=True),
    sa.Column('item_count', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('payment_gross', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('payment_fee', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('payment_net', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('payment_status', sa.String(length=30), nullable=True),
    sa.Column('txn_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.String(length=80000), nullable=True),
    sa.Column('youtube_link', sa.String(length=30), nullable=True),
    sa.Column('image_path', sa.String(length=100), nullable=True),
    sa.Column('posted_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_posted_time'), 'posts', ['posted_time'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=800), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=800), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replies_timestamp'), 'replies', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replies_timestamp'), table_name='replies')
    op.drop_table('replies')
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_posts_posted_time'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('payment')
    op.drop_table('consultation')
    op.drop_table('author')
    op.drop_table('admins')
    # ### end Alembic commands ###
